"""
Game Generator Engine
Erzeugt spielbare Mini-Games aus Ideen
"""

import os
from datetime import datetime

class GameGeneratorEngine:
    
    GAMES_DIR = "generated_games"
    
    def __init__(self):
        os.makedirs(self.GAMES_DIR, exist_ok=True)
    
    def generate_game(self, user_id, idea, genre="puzzle"):
        """
        Generate a playable mini-game from an idea
        
        Args:
            user_id (int): User ID
            idea (str): Game idea description
            genre (str): Game genre
        
        Returns:
            dict: Game metadata and file info
        """
        
        game_id = f"{user_id}_{int(datetime.now().timestamp())}"
        filename = f"{game_id}.html"
        filepath = os.path.join(self.GAMES_DIR, filename)
        
        # Generate HTML game
        html_content = self._generate_html_game(idea, genre)
        
        with open(filepath, "w") as f:
            f.write(html_content)
        
        return {
            "game_id": game_id,
            "filename": filename,
            "filepath": filepath,
            "url": f"/games/{filename}",
            "idea": idea,
            "genre": genre,
            "created_at": datetime.now().isoformat()
        }
    
    def _generate_html_game(self, idea, genre):
        """Generate HTML5 game template"""
        
        # Basis HTML5 Template
        html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{idea}</title>
    <style>
        body {{
            margin: 0;
            padding: 0;
            background: linear-gradient(135deg, #0a0a0a, #1a1a2e);
            color: white;
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }}
        
        .game-container {{
            width: 800px;
            height: 600px;
            background: #16213e;
            border: 3px solid #00ffff;
            border-radius: 10px;
            padding: 20px;
            box-shadow: 0 0 40px rgba(0, 255, 255, 0.3);
        }}
        
        h1 {{
            color: #ffd700;
            text-align: center;
            text-shadow: 0 0 20px rgba(255, 215, 0, 0.5);
        }}
        
        .game-info {{
            background: rgba(0, 255, 255, 0.1);
            padding: 15px;
            border-radius: 5px;
            margin: 20px 0;
        }}
        
        .status {{
            color: #00ffff;
            font-weight: bold;
        }}
        
        button {{
            background: #ffd700;
            color: black;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            font-weight: bold;
            margin: 10px;
            transition: 0.3s;
        }}
        
        button:hover {{
            background: #ffed4e;
            transform: scale(1.05);
        }}
        
        canvas {{
            background: black;
            border: 2px solid #00ffff;
            margin: 10px auto;
            display: block;
            border-radius: 5px;
        }}
    </style>
</head>
<body>
    <div class="game-container">
        <h1>🎮 {idea}</h1>
        
        <div class="game-info">
            <p class="status">✓ Generated by Quantum Meta Core</p>
            <p>Genre: <strong>{genre}</strong></p>
            <p>This is an auto-generated mini-game created from your imagination!</p>
        </div>
        
        <canvas id="gameCanvas" width="760" height="400"></canvas>
        
        <div style="text-align: center;">
            <button onclick="startGame()">▶ Start Game</button>
            <button onclick="resetGame()">↺ Reset</button>
            <button onclick="saveGame()">💾 Save</button>
        </div>
        
        <div id="gameLog"></div>
    </div>
    
    <script>
        const canvas = document.getElementById('gameCanvas');
        const ctx = canvas.getContext('2d');
        const gameLog = document.getElementById('gameLog');
        
        let gameActive = false;
        let score = 0;
        let playerX = canvas.width / 2;
        let playerY = canvas.height - 30;
        
        function startGame() {{
            gameActive = true;
            score = 0;
            gameLog.innerHTML = '<p style="color: #00ff00;">🎮 Game Started!</p>';
            gameLoop();
        }}
        
        function resetGame() {{
            gameActive = false;
            ctx.clearRect(0, 0, canvas.width, canvas.height);
            drawGame();
            gameLog.innerHTML = '<p style="color: #ffff00;">Game Reset</p>';
        }}
        
        function saveGame() {{
            gameLog.innerHTML = '<p style="color: #00ffff;">💾 Game Saved (Score: ' + score + ')</p>';
        }}
        
        function drawGame() {{
            // Background
            ctx.fillStyle = '#000000';
            ctx.fillRect(0, 0, canvas.width, canvas.height);
            
            // Player
            ctx.fillStyle = '#ffd700';
            ctx.fillRect(playerX, playerY, 40, 40);
            
            // Info text
            ctx.fillStyle = '#00ffff';
            ctx.font = '16px Arial';
            ctx.fillText('Score: ' + score, 10, 30);
            ctx.fillText('Idea: {idea}', 10, 60);
        }}
        
        function gameLoop() {{
            drawGame();
            
            // Simple game mechanics
            if (gameActive) {{
                score += 1;
                setTimeout(gameLoop, 50);
            }}
        }}
        
        // Keyboard input
        document.addEventListener('keydown', (e) => {{
            if (!gameActive) return;
            
            if (e.key === 'ArrowLeft' && playerX > 0) playerX -= 10;
            if (e.key === 'ArrowRight' && playerX < canvas.width - 40) playerX += 10;
        }});
        
        // Initial draw
        drawGame();
    </script>
</body>
</html>
        """
        return html

def create_game_generator():
    """Factory function"""
    return GameGeneratorEngine()

